apiVersion: v1
kind: ReplicationController
metadata:
  name: healthcheck-live
  labels:
    example: ex-03-live
spec:
  replicas: 2
  selector:
    example: ex-03-live
  template:
    metadata:
      labels:
        example: ex-03-live
    spec:
      containers:
      - name:  healthcheck-live
        image: mhart/alpine-node:8
        command: ["node"]
        args: ["index.js"]

        env:
          - name: CHECK
            value: "Liveness"

        ports:
        - containerPort: 3000

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
            httpHeaders:
            - name: X-Check-Header
              value: Liveness
          initialDelaySeconds: 5
          periodSeconds: 5

        volumeMounts:
          - name: ex-03-live
            mountPath: /index.js
            subPath: demo-server.js
      volumes:
        - name: ex-03-live
          configMap:
            name: shared