apiVersion: v1
kind: Service
metadata:
  name: healthcheck-live
  labels:
    example: ex-03-live
spec:
  type: NodePort
  #type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    example: ex-03-live