apiVersion: v1
kind: ReplicationController
metadata:
  name: healthcheck-ready
  labels:
    example: ex-03-ready
spec:
  replicas: 2
  selector:
    example: ex-03-ready
  template:
    metadata:
      labels:
        example: ex-03-ready
    spec:
      containers:
      - name:  healthcheck-ready
        image: mhart/alpine-node:8
        command: ["node"]
        args: ["index.js"]

        env:
          - name: CHECK
            value: "Readiness"

        ports:
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
            httpHeaders:
            - name: X-Check-Header
              value: Readyness
          initialDelaySeconds: 5
          periodSeconds: 5

        volumeMounts:
          - name: ex-03-ready
            mountPath: /index.js
            subPath: demo-server.js
      volumes:
        - name: ex-03-ready
          configMap:
            name: shared