apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-configmap
  labels:
    example: ex-02
spec:
  replicas: 1
  selector:
    example: ex-02
  template:
    metadata:
      labels:
        example: ex-02
    spec:
      containers:
      - name:  nginx-configmap
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: ex-02
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
      volumes:
        - name: ex-02
          configMap:
            name: ex-02