apiVersion: v1
kind: ReplicationController
metadata:
  name: lifecycle
  labels:
    example: ex-04
spec:
  replicas: 2
  selector:
    example: ex-04
  template:
    metadata:
      labels:
        example: ex-04
    spec:
      containers:
      - name:  lifecycle
        image: mhart/alpine-node:8
        command: ["node"]
        args: ["index.js"]

        lifecycle:
          postStart:
            exec:
#              command: ["/bin/ash","-c","echo 'blah'"]
              command: ["/bin/ash","-c","/bin/sleep 10 && /bin/kill -12 1"]
          preStop:
            httpGet:
#              path: http://my.registration-server.com/register/
#              port: 80
              path: /stop?delay=5
              port: 3000
        volumeMounts:
          - name: ex-04
            mountPath: /index.js
            subPath: demo-server.js
      volumes:
        - name: ex-04
          configMap:
            name: shared