apiVersion: v1
kind: Service
metadata:
  name: nginx-configmap-file
  labels:
    example: ex-02-file
spec:
  type: NodePort
  #type: LoadBalancer
  ports:
  - port: 80
  selector:
    example: ex-02-file