apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-configmap-file
  labels:
    example: ex-02-file
spec:
  replicas: 1
  selector:
    example: ex-02-file
  template:
    metadata:
      labels:
        example: ex-02-file
    spec:
      containers:
      - name:  nginx-configmap-file
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: ex-02-file
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
      volumes:
        - name: ex-02-file
          configMap:
            name: ex-02-file